# Generated by Django 3.1.6 on 2021-02-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TracePoint',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='trace_point',
            new_name='question',
        ),
    ]
