# Generated by Django 3.1.6 on 2021-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0002_auto_20210219_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text')], default='text', max_length=200),
        ),
    ]
