# Generated by Django 3.1.6 on 2021-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0003_question_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('email', 'Email')], default='text', max_length=200),
        ),
    ]
