# Generated by Django 3.1.6 on 2021-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0004_auto_20210219_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='group_size',
            field=models.IntegerField(default=0),
        ),
    ]
